# Generated by Django 5.2.6 on 2025-09-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='request_photo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
